name: grocery_admin_dashboard
description: "Admin dashboard for GroceryFlow - Store management and order processing"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  # Core UI and responsive design for admin dashboard
  sizer: ^2.0.15              # Responsive design system
  google_fonts: ^6.1.0       # Typography
  shared_preferences: ^2.2.2 # Local data storage
  
  # Admin-specific UI components
  data_table_2: ^2.5.11      # Advanced data tables for admin
  fl_chart: ^0.65.0          # Charts and analytics
  file_picker: ^8.0.0+1      # File uploads for product images
  image_picker: ^1.1.2       # Image selection for camera/gallery
  cached_network_image: ^3.3.1 # Image caching
  
  # Data management and API
  dio: ^5.4.0                # HTTP client
  connectivity_plus: ^6.1.4  # Network connectivity
  fluttertoast: ^8.2.4       # Toast notifications
  
  # Supabase integration
  supabase_flutter: ^2.5.6   # Supabase Flutter client
  flutter_dotenv: ^5.1.0     # Environment variables
  
  # Analytics (using Supabase)
  # No additional dependencies needed - using existing Supabase setup
  
  # Date and time handling
  intl: ^0.19.0              # Date formatting and localization
  
  # State management (optional, can use Provider or Riverpod)
  provider: ^6.1.1           # State management
  
  # Utilities
  uuid: ^4.5.1               # Unique ID generation
  path: ^1.9.0               # Path utilities

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
